# Generated by Django 6.0.2 on 2026-03-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('contact', models.CharField(max_length=25, unique=True, verbose_name='N° de Téléphone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Adresse email')),
                ('first_name', models.CharField(max_length=150, verbose_name='Prénom(s)')),
                ('last_name', models.CharField(max_length=150, verbose_name='Nom')),
                ('adress', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='Profession')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users_photos/', verbose_name='Photo de profil')),
                ('role', models.CharField(choices=[('DEV', 'Développeur'), ('ADMIN', 'Administrateur'), ('STAFF', 'Direction/Bureau'), ('TEACHER', 'Enseignant'), ('PARENT', 'Parent'), ('STUDENT', 'Élève'), ('OTHER', 'Autre')], default='STUDENT', max_length=10, verbose_name='Rôle')),
                ('permission', models.CharField(blank=True, max_length=255, verbose_name='Niveau de Permission')),
                ('is_active', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Accès admin Django')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_joined'],
                'permissions': [('can_view_financial_reports', 'Peut voir les rapports financiers'), ('can_edit_all_grades', 'Peut modifier toutes les notes'), ('can_manage_enrollments', 'Peut gérer les inscriptions'), ('can_access_audit_log', "Peut consulter le journal d'audit"), ('can_validate_exams', 'Peut valider les examens')],
            },
        ),
    ]
