# Generated by Django 6.0.2 on 2026-03-09 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reduction', models.SmallIntegerField(default=0, verbose_name='Pourcentage de la réduction')),
                ('montant_paiement', models.BigIntegerField(default=0, verbose_name='Montant dû après réduction')),
                ('tranche1', models.BigIntegerField(default=0, verbose_name='Montant de la tranche 1')),
                ('tranche2', models.BigIntegerField(default=0, verbose_name='Montant de la tranche 2')),
                ('tranche3', models.BigIntegerField(default=0, verbose_name='Montant de la tranche 3')),
                ('affectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.affectation', verbose_name='Affectation')),
            ],
        ),
        migrations.CreateModel(
            name='Versement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.BigIntegerField(default=0, verbose_name='Montant du versement')),
                ('date_versement', models.DateTimeField(auto_now_add=True)),
                ('reference_recu', models.CharField(editable=False, max_length=100, unique=True)),
                ('mode_paiement', models.CharField(choices=[('CASH', 'Espèces'), ('OM', 'Orange Money'), ('MOMO', 'Mobile Money'), ('VIREMENT', 'Virement'), ('CHEQUE', 'Chèque'), ('CARD', 'Carte bancaire'), ('AUT', 'Autre')], default='CASH', max_length=20)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versements', to='billing.paiement')),
            ],
        ),
        migrations.CreateModel(
            name='FraisScolarite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.BigIntegerField(default=0, verbose_name='Montant des frais de scolarité')),
                ('tranche1', models.BigIntegerField(default=0, verbose_name='Tranche 1')),
                ('tranche2', models.BigIntegerField(default=0, verbose_name='Tranche 2')),
                ('tranche3', models.BigIntegerField(default=0, verbose_name='Tranche 3')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.anneescolaire', verbose_name='Année scolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classe', verbose_name='Classe')),
            ],
            options={
                'verbose_name': 'Frais de scolarité',
                'verbose_name_plural': 'Frais de scolarité',
                'unique_together': {('classe', 'annee_scolaire')},
            },
        ),
    ]
