# Generated by Django 6.0.2 on 2026-03-09 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Note 1')),
                ('note2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Note 2')),
                ('moyenne', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Moyenne')),
                ('appreciation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Appréciation')),
                ('affectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.affectation', verbose_name='Affectation')),
                ('matiereclasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.matiereclasse', verbose_name='Matière-Classe')),
                ('periodicite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.periode', verbose_name='Période')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'unique_together': {('affectation', 'matiereclasse', 'periodicite')},
            },
        ),
    ]
