# Generated by Django 6.0.3 on 2026-03-10 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
        ('grading', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinAnnuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne_annuelle', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Moyenne annuelle')),
                ('rang', models.CharField(blank=True, max_length=20, null=True, verbose_name='Rang annuel')),
                ('appreciation_annuelle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Appréciation annuelle')),
                ('date_calcul', models.DateTimeField(auto_now_add=True, verbose_name='Date de calcul')),
                ('affectation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enrollment.affectation', verbose_name='Affectation')),
            ],
            options={
                'verbose_name': 'Bulletin annuel',
                'verbose_name_plural': 'Bulletins annuels',
            },
        ),
        migrations.CreateModel(
            name='BulletinPeriode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne_generale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Moyenne générale')),
                ('rang', models.CharField(blank=True, max_length=20, null=True, verbose_name='Rang')),
                ('appreciation_generale', models.CharField(blank=True, max_length=255, null=True, verbose_name='Appréciation générale')),
                ('details_notes', models.JSONField(default=dict, verbose_name='Détails des notes par matière')),
                ('stats_classe', models.JSONField(default=dict, verbose_name='Statistiques de la classe')),
                ('date_calcul', models.DateTimeField(auto_now_add=True, verbose_name='Date de calcul')),
                ('affectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.affectation', verbose_name='Affectation')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.periode', verbose_name='Période')),
            ],
            options={
                'verbose_name': 'Bulletin périodique',
                'verbose_name_plural': 'Bulletins périodiques',
                'unique_together': {('affectation', 'periode')},
            },
        ),
    ]
