# Generated by Django 6.0.3 on 2026-03-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_bulletinannuel_bulletinperiode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='moyenne',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Moyenne'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note1',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Note 1'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note2',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Note 2'),
        ),
    ]
