# Generated by Django 6.0.2 on 2026-03-09 23:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(blank=True, max_length=9, null=True, unique=True, verbose_name='Année scolaire')),
                ('debut_annee', models.IntegerField(verbose_name='Année de début')),
                ('fin_annee', models.IntegerField(verbose_name='Année de fin')),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la classe')),
                ('cycle_scolaire', models.CharField(choices=[('Crèche', 'Crèche'), ('Maternelle', 'Maternelle'), ('Primaire', 'Primaire'), ('Collège', 'Collège'), ('Lycée', 'Lycée'), ('Université', 'Université'), ('Autre', 'Autre')], max_length=20, verbose_name='Cycle scolaire')),
                ('option_scolaire', models.CharField(blank=True, choices=[('Sciences expérimentales', 'Sciences expérimentales'), ('Sciences mathématiques', 'Sciences mathématiques'), ('Sciences sociales', 'Sciences sociales'), ('Scientifique', 'Scientifique'), ('Littéraire', 'Littéraire'), ('Technique', 'Technique'), ('Générale', 'Générale'), ('Tron commun', 'Tron commun'), ('Autre', 'Autre'), ('Sans option', 'Sans option')], max_length=30, null=True, verbose_name='Option scolaire')),
                ('est_active', models.BooleanField(default=True, verbose_name='Classe active')),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la matière')),
                ('est_active', models.BooleanField(default=True, verbose_name='Matière active')),
            ],
        ),
        migrations.CreateModel(
            name='MatiereClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Coefficient')),
                ('est_active', models.BooleanField(default=True, verbose_name='Matière active dans la classe')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres_classe', to='school.anneescolaire', verbose_name='Année scolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres_classe', to='school.classe', verbose_name='Classe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_matiere', to='school.matiere', verbose_name='Matière')),
                ('professeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matieres_enseignees', to='people.teacher', verbose_name='Professeur')),
            ],
            options={
                'ordering': ['annee_scolaire__debut_annee', 'classe__nom', 'matiere__nom'],
                'unique_together': {('annee_scolaire', 'classe', 'matiere')},
            },
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_scolaire', models.CharField(choices=[('Crèche', 'Crèche'), ('Maternelle', 'Maternelle'), ('Primaire', 'Primaire'), ('Collège', 'Collège'), ('Lycée', 'Lycée'), ('Université', 'Université'), ('Autre', 'Autre')], max_length=20, verbose_name='Cycle scolaire')),
                ('type_periode', models.CharField(choices=[('Trimestre', 'Trimestre'), ('Semestre', 'Semestre'), ('Année', 'Année'), ('Autre', 'Autre')], max_length=20, verbose_name='Type de période')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom de la période (ex: 1er trimestre, 2ème semestre, etc.)')),
                ('ordre', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name="Ordre de la période dans l'année scolaire (ex: 1 pour le 1er trimestre, 2 pour le 2ème trimestre, etc.)")),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes', to='school.anneescolaire', verbose_name='Année scolaire')),
            ],
            options={
                'unique_together': {('annee_scolaire', 'cycle_scolaire', 'type_periode', 'nom')},
            },
        ),
    ]
