# Generated by Django 6.0.2 on 2026-03-09 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_incident', models.CharField(choices=[('ABSENCE', 'Absence'), ('RETARD', 'Retard'), ('COMPORTEMENT', 'Comportement/Indiscipline'), ('PRESENCE', 'Présence Exceptionnelle')], default='ABSENCE', max_length=20)),
                ('justifie', models.BooleanField(default=False, verbose_name='Justifié ?')),
                ('date_infraction', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'infraction")),
                ('type_infraction', models.CharField(choices=[('Absence injustifiée', 'Absence injustifiée'), ('Retard', 'Retard'), ('Comportement inapproprié', 'Comportement inapproprié')], max_length=255, verbose_name="Type d'infraction")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Détails / Motif')),
                ('sanction', models.CharField(max_length=255, verbose_name='Sanction appliquée')),
                ('points_perdus', models.PositiveIntegerField(default=0, help_text='Nombre de points à retirer du capital de 20')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Détails / Motif')),
                ('affectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.affectation', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Discipline',
                'verbose_name_plural': 'Discipline',
                'ordering': ['-date_infraction'],
            },
        ),
    ]
