# Generated by Django 6.0.2 on 2026-03-09 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_affectation', models.CharField(choices=[('INSCRIPTION', 'Inscription'), ('REINSCRIPTION', 'Réinscription'), ('AUTRE', 'Autre')], max_length=20, verbose_name="Type d'affectation")),
                ('frais_type', models.IntegerField(default=0, verbose_name="Frais de type d'affectation")),
                ('etat_affectation', models.CharField(choices=[('NOUVEAU', 'Nouveau/lle'), ('ADMIS', 'Admis/e'), ('NON_ADMIS', 'Non admis/e'), ('REDOUBLANT', 'Redoublant/e'), ('CANDIDAT_LIBRE', 'Candidat/e libre'), ('TRANSFERE', 'Transféré/e'), ('AUTRE', 'Autre')], max_length=20, verbose_name="État de l'affectation")),
                ('date_affectation', models.DateField(auto_now_add=True, verbose_name="Date d'affectation")),
                ('statut_affectation', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('ABANDON', 'Abandon'), ('TRANSFERE', 'Transféré/e')], max_length=20, verbose_name="Statut de l'affectation")),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.anneescolaire', verbose_name='Année scolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classe', verbose_name='Classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.student', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Affectation',
                'verbose_name_plural': 'Affectations',
                'unique_together': {('eleve', 'annee_scolaire')},
            },
        ),
    ]
